---
apiVersion: v1
kind: Namespace
metadata:
  name: trufflehonk
  labels:
    app.kubernetes.io/name: trufflehonk
    app.kubernetes.io/part-of: trufflehonk

---
apiVersion: v1
kind: Secret
data:
  # figure it out yourself
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  TRUFFLEHONK_OUTPUT_S3_BUCKET_NAME:
  TRUFFLEHONK_QUEUE_SQS_URL:
metadata:
  name: trufflehonk-job-secret
  namespace: trufflehonk

---
apiVersion: batch/v1
kind: Job
metadata:
  name: trufflehonk-worker
  namespace: trufflehonk
  labels:
    app.kubernetes.io/name: trufflehonk-job
    app.kubernetes.io/part-of: trufflehonk
spec:
  parallelism: 5
  # keep finished jobs for an hour before deleting
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      name: trufflehonk-job
    spec:
      containers:
      - name: trufflehonk-worker
        image: trufflehonk:v0.1.1
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: trufflehonk-job-secret
      restartPolicy: OnFailure
