#!/usr/bin/env python3
import os
import sys
import tempfile

from trufflehonk.jobs import trufflehog, pydriller
from trufflehonk.utils import github_org_repos, update_dict_sets


def honk_github(org, repos=None, clone_dir=None, user=False):
    secrets = []
    author_emails = dict()
    tempdir = None

    if not clone_dir:
        tempdir = tempfile.TemporaryDirectory()
        tempdir.name
        print(f'cloning repos into temporary directory {tempdir.name}')
        clone_dir = tempdir.name

    if not repos:
        repos = github_org_repos(org, user=True)

    for repo in repos:
        try:
            repo_url = f'https://github.com/{org}/{repo}'
            clone_dir = os.path.join(clone_dir, org, repo)

            tf = trufflehog.Trufflehog(repo_url, clone_dir)
            pd = pydriller.PyDriller(repo_url, clone_dir)

            print(f'processing {repo_url}', file=sys.stderr)

            tf.run()
            pd.run()

            secrets += tf.output
            update_dict_sets(author_emails, pd.output)
        except KeyboardInterrupt:
            break
        except Exception as e:
            # I don't know what exceptions can happen tbh
            print(e)

    print('secrets')
    print('============================')
    print(trufflehog.output_human(secrets))
    print('commit authors')
    print('============================')
    print(pydriller.output_human(author_emails))


def honk_github_cmd(args):
    honk_github(args.org, args.repos, args.clone_dir, args.user)


def commastring(s):
    return s.split(',')


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser('trufflehonk')
    parser.set_defaults(func=None)

    subparsers = parser.add_subparsers(title='subcommands')

    honk_subparser = subparsers.add_parser('honk', aliases=['scan'])
    honk_subparser.add_argument('org', metavar='NAME', help='name of org or user')
    honk_subparser.add_argument('--repos', help='comma-separated list of repos', type=commastring, default=None)
    honk_subparser.add_argument('--user', help='set if the username belongs to a user (github api limitation)', action='store_true', default=False)
    honk_subparser.add_argument('--clone-dir', help='basedir to clone into', default=None)
    honk_subparser.add_argument('--no-cumulative', help='don\'t print a cumulative report (output each repo separately)', default=False)
    honk_subparser.set_defaults(func=honk_github_cmd)

    args = parser.parse_args()

    if args.func:
        args.func(args)
    else:
        parser.print_usage()
